#!/usr/bin/env bash
# demo.sh — One-click MarkSync demo: create/update → commit → sync → verify
#
# Supports two flows:
#   1. NEW PAGE:   ./demo.sh my-new-page    → creates docs/my-new-page.md, syncs
#   2. UPDATE:     ./demo.sh hello-world    → edits existing page, syncs
#   3. SYNC ONLY:  ./demo.sh --sync         → just runs sync (no edits)
#
# Page name accepts: "my-page", "docs/my-page", "docs/my-page.md" — all normalize
# to docs/my-page.md.
#
# After sync, lists ALL Confluence page links from the lock file.
#
# Prerequisites:
#   - MARKSYNC_SRC env var pointing to the marksync source repo
#   - .env file with Confluence credentials
#   - marksync.yml configured with target space + parent page

set -euo pipefail

MARKSYNC_SRC="${MARKSYNC_SRC:-$(realpath ../marksync-for-confluence)}"
DEMO_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DEMO_DIR"

# ─── Colors ───
G='\033[0;32m'   # green
Y='\033[1;33m'   # yellow
C='\033[0;36m'   # cyan
B='\033[1m'      # bold
R='\033[0;31m'   # red
N='\033[0m'      # reset

banner() {
    echo -e "${C}${B}═══════════════════════════════════════════════════════${N}"
    echo -e "${C}${B}  $1${N}"
    echo -e "${C}${B}═══════════════════════════════════════════════════════${N}"
}

banner "MarkSync for Confluence — Live Demo"
echo ""

# ─── Normalize page name ───
ARG="${1:-}"

if [ "$ARG" = "--sync" ] || [ -z "$ARG" ]; then
    MODE="sync-only"
    MARKDOWN_FILE=""
else
    # Strip docs/ prefix and .md suffix
    PAGE_NAME="${ARG#docs/}"
    PAGE_NAME="${PAGE_NAME%.md}"
    MARKDOWN_FILE="docs/${PAGE_NAME}.md"

    if [ -f "$MARKDOWN_FILE" ]; then
        MODE="update"
    else
        MODE="create"
    fi
fi

echo -e "${Y}Mode: ${B}$MODE${N}" $([ -n "$MARKDOWN_FILE" ] && echo "→ $MARKDOWN_FILE")
echo ""

# ─── Step 1: Show current state ───
echo -e "${Y}▸ Step 1: Current state${N}"
if [ -f marksync.lock.yml ]; then
    PAGE_COUNT=$(grep -c 'sourcePath:' marksync.lock.yml 2>/dev/null || echo "0")
    echo "  Lock file: $PAGE_COUNT page(s) tracked"
else
    echo "  No lock file yet — first sync will create pages."
fi
echo "  Markdown files: $(ls docs/*.md 2>/dev/null | wc -l) in docs/"
echo ""

# ─── Step 2: Create or update the page ───
if [ "$MODE" = "create" ]; then
    echo -e "${Y}▸ Step 2: Creating new page $MARKDOWN_FILE${N}"

    # Generate UUID v7 using marksync's own generator
    UUID=$(bun "$MARKSYNC_SRC/src/domain/identity/uuid.ts" 2>/dev/null || true)
    if [ -z "$UUID" ]; then
        # Fallback: generate via inline bun
        UUID=$(bun -e "import { generateUuidV7 } from '$MARKSYNC_SRC/src/domain/identity/uuid.ts'; console.log(generateUuidV7());" 2>/dev/null || echo "")
    fi
    if [ -z "$UUID" ]; then
        # Last resort: simple uuidgen
        UUID=$(uuidgen 2>/dev/null || echo "00000000-0000-7000-8000-000000000000")
    fi

    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

    mkdir -p docs
    cat > "$MARKDOWN_FILE" << PAGEEOF
---
marksync:
  uuid: $UUID
---

# ${PAGE_NAME}

This page was created by the **MarkSync demo** to show how new pages are
published to Confluence from Git-tracked Markdown.

## Details

- **Created:** ${TIMESTAMP}
- **Source:** \`docs/${PAGE_NAME}.md\`
- **UUID:** \`${UUID}\`

## Why This Works

1. Write Markdown in Git
2. Run \`marksync sync\`
3. Page appears on Confluence — automatically

## Code Sample

\`\`\`python
def greet(name: str) -> str:
    return f"Hello from {name}!"
\`\`\`

## Status

| Item | Value |
|------|-------|
| Synced via | marksync CLI |
| Format | Storage XHTML |
| Identity | UUID v7 |

---
*Auto-generated by demo.sh*
PAGEEOF

    echo "  Generated UUID: $UUID"
    echo "  ✅ Created $MARKDOWN_FILE"

elif [ "$MODE" = "update" ]; then
    echo -e "${Y}▸ Step 2: Updating $MARKDOWN_FILE${N}"
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S %Z')

    # Update the live-update section (replace if exists, or append)
    python3 -c "
import re
with open('$MARKDOWN_FILE', 'r') as f:
    content = f.read()
# Remove existing update section
content = re.sub(r'\n## 🔄 Live Update.*?(?=\n---\n|\n\*Auto-generated|\Z)', '', content, flags=re.DOTALL)
update = '''

## 🔄 Live Update

**Last synced:** $TIMESTAMP

This section is automatically updated by \`demo.sh\` to demonstrate the
marksync update flow. Each run produces a new page version on Confluence.
'''
# Insert before the final separator or at the end
if '---\n*Auto-generated' in content:
    content = content.replace('---\n*Auto-generated', update + '---\n*Auto-generated')
elif content.rstrip().endswith('---'):
    content = content.rstrip()[:-3] + update + '\n---\n'
else:
    content = content.rstrip() + update + '\n'
with open('$MARKDOWN_FILE', 'w') as f:
    f.write(content)
"
    echo "  Updated at: $TIMESTAMP"
    echo "  ✅ $MARKDOWN_FILE modified"

else
    echo -e "${Y}▸ Step 2: Sync only (no file edits)${N}"
fi
echo ""

# ─── Step 3: Git commit ───
if [ "$MODE" != "sync-only" ]; then
    echo -e "${Y}▸ Step 3: Git commit${N}"
    git add "$MARKDOWN_FILE"
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
    git commit -m "demo: $MODE ${PAGE_NAME:-page} at ${TIMESTAMP}" --quiet
    echo "  $(git log --oneline -1)"
    echo ""
else
    # Still commit the lock if it changed
    if [ -n "$(git status --porcelain marksync.lock.yml 2>/dev/null)" ]; then
        git add marksync.lock.yml
        git commit -m "demo: sync lock update" --quiet 2>/dev/null || true
    fi
fi

# ─── Step 4: Run marksync sync ───
echo -e "${Y}▸ Step 4: marksync sync${N}"
echo ""
OUTPUT=$(bun "$MARKSYNC_SRC/src/cli/index.ts" sync 2>&1) || true

echo "$OUTPUT"

# Parse and display results
python3 -c "
import json, sys
raw = '''$OUTPUT'''
# Extract the JSON data line
for line in raw.split('\n'):
    if line.startswith('data: '):
        try:
            data = json.loads(line[6:])
            results = data.get('results', [])
            for r in results:
                outcome = r.get('outcome', '?')
                uuid = r.get('uuid', '?')[:8]
                err = r.get('error', {})
                err_kind = err.get('kind', '')
                icon = {'created': '✨', 'updated': '📝', 'noop': '⏭️', 'blocked': '⚠️', 'skipped': '⏭️'}.get(outcome, '?')
                line = f'  {icon} {outcome:8s} {uuid}'
                if err_kind:
                    line += f'  ({err_kind})'
                print(line)
            print()
            w = data.get('writes', 0)
            s = data.get('skips', 0)
            b = data.get('blocks', 0)
            print(f'  Summary: {w} writes, {s} skips, {b} blocks')
        except:
            pass
        break
else:
    # No data line found — show raw output
    print(raw[:500])
" 2>&1
echo ""

# ─── Step 5: List ALL Confluence pages ───
echo -e "${Y}▸ Step 5: All synchronized Confluence pages${N}"
echo ""
if [ -f marksync.lock.yml ] && [ -f .env ]; then
    BASE_URL=$(grep MARKSYNC_CONFLUENCE_BASE_URL .env 2>/dev/null | head -1 | cut -d= -f2 || echo "")
    python3 -c "
import yaml, sys
with open('marksync.lock.yml') as f:
    lock = yaml.safe_load(f)
base_url = '$BASE_URL'
targets = lock.get('targets', {})
idx = 0
for tid, tdata in sorted(targets.items()):
    docs = tdata.get('documents', {})
    for uuid, binding in sorted(docs.items(), key=lambda x: x[1].get('sourcePath', '')):
        idx += 1
        src = binding.get('sourcePath', '?')
        page_id = binding.get('pageId', '?')
        version = binding.get('pageVersion', '?')
        url = f'{base_url}/wiki/pages/viewpage.action?pageId={page_id}'
        print(f'  📄 [{idx}] {src}')
        print(f'     v{version}  →  {url}')
        print()
if idx == 0:
    print('  (no pages in lock file)')
" 2>&1
else
    echo "  (no lock file or .env found)"
fi

echo ""
banner "Demo complete"
